#!/usr/bin/env python3
"""
Interactive .gitignore builder — blessed edition (cross-platform).

Install dep:  pip install blessed

- Everything is IGNORED by default.
- Navigate with ↑/↓ arrow keys.
- Press SPACE to whitelist (allow) an item.
- Press ENTER or → to drill into a directory.
- Press ← or ESC to go back up.
- Press D to finish and write .gitignore.
- Press Q to quit without writing.
"""

import os
import sys
from pathlib import Path

try:
    from blessed import Terminal
except ImportError:
    print("Missing dependency: run  pip install blessed")
    sys.exit(1)

# ── State ──────────────────────────────────────────────────────────────────────

whitelisted: set[str] = set()
ROOT = Path(".")
term = Terminal()

# FIX 1 — descendant cache: rglob is only run once per directory path,
# then reused on every render. Cleared only when toggle() mutates state.
_desc_cache: dict[str, list[str]] = {}

# ── File-tree helpers ──────────────────────────────────────────────────────────

def list_dir(rel_path: str) -> list[dict]:
    base = ROOT / rel_path if rel_path else ROOT
    try:
        entries = sorted(base.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower()))
    except PermissionError:
        return []
    result = []
    for e in entries:
        if e.name in (".git",):
            continue
        rp = str(e.relative_to(ROOT))
        result.append({"name": e.name, "path": rp, "is_dir": e.is_dir()})
    return result


def get_descendants(rel_path: str) -> list[str]:
    """Cached rglob — disk walk happens once per path, not once per keypress."""
    if rel_path not in _desc_cache:
        base = ROOT / rel_path
        result = []
        for p in base.rglob("*"):
            if ".git" in p.parts:
                continue
            result.append(str(p.relative_to(ROOT)))
        _desc_cache[rel_path] = result
    return _desc_cache[rel_path]


def is_fully_whitelisted(entry: dict) -> bool:
    if not entry["is_dir"]:
        return entry["path"] in whitelisted
    desc = get_descendants(entry["path"])
    return entry["path"] in whitelisted and all(d in whitelisted for d in desc)


def is_partially_whitelisted(entry: dict) -> bool:
    if not entry["is_dir"]:
        return False
    desc = get_descendants(entry["path"])
    wl_count = sum(1 for d in desc if d in whitelisted)
    total = len(desc) + (1 if entry["path"] in whitelisted else 0)
    return 0 < wl_count < total


def toggle(entry: dict) -> None:
    path = entry["path"]
    # Invalidate cache for this path so state is recomputed after mutation
    _desc_cache.pop(path, None)
    if entry["is_dir"]:
        desc = get_descendants(path)
        all_paths = [path] + desc
        if all(p in whitelisted for p in all_paths):
            for p in all_paths:
                whitelisted.discard(p)
        else:
            for p in all_paths:
                whitelisted.add(p)
    else:
        if path in whitelisted:
            whitelisted.discard(path)
        else:
            whitelisted.add(path)


# ── .gitignore generation ──────────────────────────────────────────────────────

def build_gitignore() -> str:
    lines = [
        "# Generated by gitignore_builder.py",
        "# Everything is ignored by default; whitelisted paths are negated.",
        "",
        "/*",
        "",
    ]
    to_negate: set[str] = set()
    for p in sorted(whitelisted):
        parts = Path(p).parts
        for i in range(1, len(parts) + 1):
            to_negate.add(str(Path(*parts[:i])))

    for p in sorted(to_negate, key=lambda x: (x.count(os.sep), x)):
        lines.append(f"!/{p}")

    return "\n".join(lines) + "\n"


# ── Rendering helpers ──────────────────────────────────────────────────────────

def clamp(val: int, lo: int, hi: int) -> int:
    return max(lo, min(hi, val))


# FIX 3 — pre-compute escape prefix/suffix strings once at import time.
# Calling term.green(line) rebuilds escape codes on every call; storing the
# raw open/close sequences and doing simple concatenation is much faster.
_C = {
    "green":       (term.green,       term.normal),
    "green_bold":  (term.green_bold,  term.normal),
    "yellow":      (term.yellow,      term.normal),
    "yellow_bold": (term.yellow_bold, term.normal),
    "red":         (term.red,         term.normal),
    "red_bold":    (term.red_bold,    term.normal),
    "cyan":        (term.cyan,        term.normal),
    "cyan_bold":   (term.cyan_bold,   term.normal),
    "blue":        (term.blue,        term.normal),
    "white":       (term.white,       term.normal),
}

def _paint(key: str, text: str, reverse: bool = False) -> str:
    open_seq, close_seq = _C[key]
    if reverse:
        return term.reverse + open_seq + text + close_seq + term.normal
    return open_seq + text + close_seq


# FIX 2 — dirty-line diffing: track what was last written to each row.
# Only rows whose content has changed are written to stdout, cutting the
# number of write() calls on a simple cursor move from ~N to just 2.
_screen_cache: dict[int, str] = {}


def _emit_line(row: int, content: str, out: list[str]) -> None:
    """Append a move+content sequence only if the line changed."""
    if _screen_cache.get(row) != content:
        out.append(term.move(row, 0) + content)
        _screen_cache[row] = content


def render(dir_stack: list[str], entries: list[dict], cursor: int) -> None:
    w = term.width or 80
    h = term.height or 24
    out: list[str] = []

    # ── Header ──
    cur_path = dir_stack[-1] if dir_stack else "."
    header = f" gitignore builder  [{cur_path}]"
    _emit_line(0, _paint("cyan_bold", header[:w - 1].ljust(w - 1)), out)

    # ── Help bar ──
    help_text = " ↑/↓ Navigate  SPACE Toggle  ENTER/→ Open dir  ← Back  D Done  Q Quit"
    _emit_line(1, _paint("white", help_text[:w - 1].ljust(w - 1)), out)

    # ── Separator ──
    _emit_line(2, _paint("blue", "─" * (w - 1)), out)

    # ── Entry list ──
    list_h = h - 5
    scroll_top = clamp(cursor - list_h // 2, 0, max(0, len(entries) - list_h))
    visible = entries[scroll_top: scroll_top + list_h]

    for i, entry in enumerate(visible):
        real_i = i + scroll_top

        full_wl = is_fully_whitelisted(entry)
        part_wl = is_partially_whitelisted(entry)

        if entry["is_dir"]:
            icon = "▷ " if full_wl else ("◈ " if part_wl else "▶ ")
            suffix = "/"
        else:
            icon = "  "
            suffix = ""

        if full_wl:
            status, color, color_bold = "✓ ", "green", "green_bold"
        elif part_wl:
            status, color, color_bold = "~ ", "yellow", "yellow_bold"
        else:
            status, color, color_bold = "✗ ", "red", "red_bold"

        line = f" {status}{icon}{entry['name']}{suffix}"
        line = line[:w - 1].ljust(w - 1)

        if real_i == cursor:
            rendered = _paint(color_bold, line, reverse=True)
        else:
            rendered = _paint(color, line)

        _emit_line(3 + i, rendered, out)

    # Clear leftover rows below the visible list
    blank = " " * (w - 1)
    for i in range(len(visible), list_h):
        _emit_line(3 + i, blank, out)

    # ── Footer ──
    footer = f" {len(whitelisted)} path(s) whitelisted  |  D = Done"
    _emit_line(h - 2, _paint("blue", "─" * (w - 1)), out)
    _emit_line(h - 1, _paint("cyan", footer[:w - 1].ljust(w - 1)), out)

    if out:
        print("".join(out), end="", flush=True)


def render_done_dialog(gitignore_text: str) -> bool:
    """Full-screen preview. Returns True if user confirms with Y."""
    w = term.width or 80
    h = term.height or 24
    lines = gitignore_text.splitlines()

    out = [term.clear]

    title = " Preview .gitignore "
    out.append(term.move(0, 0) + term.cyan_bold(title.center(w - 1)))
    out.append(term.move(1, 0) + term.blue("─" * (w - 1)))

    max_lines = h - 6
    for i, line in enumerate(lines[:max_lines]):
        out.append(term.move(2 + i, 2) + term.white(line[:w - 4]))

    if len(lines) > max_lines:
        out.append(
            term.move(2 + max_lines, 2)
            + term.yellow(f"  ... ({len(lines) - max_lines} more lines)")
        )

    out.append(term.move(h - 3, 0) + term.blue("─" * (w - 1)))
    prompt = " Write .gitignore? [Y]es / [N]o "
    out.append(
        term.move(h - 2, (w - len(prompt)) // 2) + term.green_bold(prompt)
    )

    print("".join(out), end="", flush=True)

    with term.cbreak():
        while True:
            key = term.inkey()
            if key.lower() == "y":
                return True
            if key.lower() == "n" or key.name == "KEY_ESCAPE":
                return False


# ── Main loop ─────────────────────────────────────────────────────────────────

def run() -> None:
    dir_stack: list[str] = []
    cursor_stack: list[int] = []
    cursor = 0
    result: str | None = None

    def current_rel() -> str:
        return dir_stack[-1] if dir_stack else ""

    entries = list_dir(current_rel())

    with term.fullscreen(), term.cbreak(), term.hidden_cursor():
        while True:
            if not entries:
                entries = [{"name": "(empty)", "path": "", "is_dir": False}]
            cursor = clamp(cursor, 0, len(entries) - 1)
            render(dir_stack, entries, cursor)

            key = term.inkey()

            if key.name == "KEY_UP" or str(key) == "k":
                cursor = max(0, cursor - 1)

            elif key.name == "KEY_DOWN" or str(key) == "j":
                cursor = min(len(entries) - 1, cursor + 1)

            elif str(key) == " ":
                entry = entries[cursor]
                if entry["path"]:
                    toggle(entry)
                    _screen_cache.clear()  # state changed — invalidate diff cache

            elif key.name in ("KEY_RIGHT", "KEY_ENTER") or str(key) in ("\n", "\r", "l"):
                entry = entries[cursor]
                if entry["is_dir"] and entry["path"]:
                    cursor_stack.append(cursor)
                    dir_stack.append(entry["path"])
                    entries = list_dir(entry["path"])
                    cursor = 0
                    _screen_cache.clear()  # new directory view

            elif key.name in ("KEY_LEFT", "KEY_ESCAPE") or str(key) == "h":
                if dir_stack:
                    dir_stack.pop()
                    cursor = cursor_stack.pop() if cursor_stack else 0
                    entries = list_dir(current_rel())
                    _screen_cache.clear()  # returning to parent view

            elif str(key).lower() == "d":
                gitignore_text = build_gitignore()
                confirmed = render_done_dialog(gitignore_text)
                if confirmed:
                    result = gitignore_text
                    break

            elif str(key).lower() == "q":
                break

    if result is None:
        print("Aborted. No .gitignore written.")
        sys.exit(0)

    out_path = Path(".gitignore")
    out_path.write_text(result)
    print(f"✓ Written to {out_path.resolve()}")
    print(f"  {len(result.splitlines())} lines, {len(whitelisted)} path(s) whitelisted.")


if __name__ == "__main__":
    run()
